name: Bug Report
description: Report a bug or issue with the payOS Python SDK
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and reproduce the issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here...
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What went wrong?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: payOS SDK Version
      description: Which version of the payOS Python SDK are you using?
      placeholder: e.g., 1.2.3
    validations:
      required: true
  - type: input
    id: env-version
    attributes:
      label: Python Version
      description: Which Python version are you using?
      placeholder: e.g., Python 3.12
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      placeholder: e.g., macOS 12.6, Windows 11, Ubuntu 22.04
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as error messages, stack traces, or screenshots.
      placeholder: Any additional information that might help us understand the issue.
